---
- name: Configure Keepalived
  template:
    src: etc-keepalived-keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    # backup: yes
  notify: restart keepalived
  tags: keepalived

- name: Ensure service is started and enabled
  service:
    name: "{{ keepalived_service_name }}"
    state: started
    enabled: yes
  tags: keepalived

# vim:ft=ansible:
